package pers.meng.domain.bean;

import java.io.Serializable;
import java.util.Date;

public class entInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.entname
     *
     * @mbggenerated
     */
    private String entname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.entlocation
     *
     * @mbggenerated
     */
    private String entlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.entbusiness
     *
     * @mbggenerated
     */
    private String entbusiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.entperson
     *
     * @mbggenerated
     */
    private String entperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.enttype
     *
     * @mbggenerated
     */
    private String enttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.interviewstudent
     *
     * @mbggenerated
     */
    private String interviewstudent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.interviewaspect
     *
     * @mbggenerated
     */
    private String interviewaspect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.studentclass
     *
     * @mbggenerated
     */
    private String studentclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.entwhite
     *
     * @mbggenerated
     */
    private String entwhite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.GMT_CREATE
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ent_info.GMT_MODIFIED
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.id
     *
     * @return the value of ent_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.id
     *
     * @param id the value for ent_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.entname
     *
     * @return the value of ent_info.entname
     *
     * @mbggenerated
     */
    public String getEntname() {
        return entname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.entname
     *
     * @param entname the value for ent_info.entname
     *
     * @mbggenerated
     */
    public void setEntname(String entname) {
        this.entname = entname == null ? null : entname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.entlocation
     *
     * @return the value of ent_info.entlocation
     *
     * @mbggenerated
     */
    public String getEntlocation() {
        return entlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.entlocation
     *
     * @param entlocation the value for ent_info.entlocation
     *
     * @mbggenerated
     */
    public void setEntlocation(String entlocation) {
        this.entlocation = entlocation == null ? null : entlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.entbusiness
     *
     * @return the value of ent_info.entbusiness
     *
     * @mbggenerated
     */
    public String getEntbusiness() {
        return entbusiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.entbusiness
     *
     * @param entbusiness the value for ent_info.entbusiness
     *
     * @mbggenerated
     */
    public void setEntbusiness(String entbusiness) {
        this.entbusiness = entbusiness == null ? null : entbusiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.entperson
     *
     * @return the value of ent_info.entperson
     *
     * @mbggenerated
     */
    public String getEntperson() {
        return entperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.entperson
     *
     * @param entperson the value for ent_info.entperson
     *
     * @mbggenerated
     */
    public void setEntperson(String entperson) {
        this.entperson = entperson == null ? null : entperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.enttype
     *
     * @return the value of ent_info.enttype
     *
     * @mbggenerated
     */
    public String getEnttype() {
        return enttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.enttype
     *
     * @param enttype the value for ent_info.enttype
     *
     * @mbggenerated
     */
    public void setEnttype(String enttype) {
        this.enttype = enttype == null ? null : enttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.interviewstudent
     *
     * @return the value of ent_info.interviewstudent
     *
     * @mbggenerated
     */
    public String getInterviewstudent() {
        return interviewstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.interviewstudent
     *
     * @param interviewstudent the value for ent_info.interviewstudent
     *
     * @mbggenerated
     */
    public void setInterviewstudent(String interviewstudent) {
        this.interviewstudent = interviewstudent == null ? null : interviewstudent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.interviewaspect
     *
     * @return the value of ent_info.interviewaspect
     *
     * @mbggenerated
     */
    public String getInterviewaspect() {
        return interviewaspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.interviewaspect
     *
     * @param interviewaspect the value for ent_info.interviewaspect
     *
     * @mbggenerated
     */
    public void setInterviewaspect(String interviewaspect) {
        this.interviewaspect = interviewaspect == null ? null : interviewaspect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.studentclass
     *
     * @return the value of ent_info.studentclass
     *
     * @mbggenerated
     */
    public String getStudentclass() {
        return studentclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.studentclass
     *
     * @param studentclass the value for ent_info.studentclass
     *
     * @mbggenerated
     */
    public void setStudentclass(String studentclass) {
        this.studentclass = studentclass == null ? null : studentclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.entwhite
     *
     * @return the value of ent_info.entwhite
     *
     * @mbggenerated
     */
    public String getEntwhite() {
        return entwhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.entwhite
     *
     * @param entwhite the value for ent_info.entwhite
     *
     * @mbggenerated
     */
    public void setEntwhite(String entwhite) {
        this.entwhite = entwhite == null ? null : entwhite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.remark
     *
     * @return the value of ent_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.remark
     *
     * @param remark the value for ent_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.GMT_CREATE
     *
     * @return the value of ent_info.GMT_CREATE
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.GMT_CREATE
     *
     * @param gmtCreate the value for ent_info.GMT_CREATE
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_info.GMT_MODIFIED
     *
     * @return the value of ent_info.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_info.GMT_MODIFIED
     *
     * @param gmtModified the value for ent_info.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        entInfo other = (entInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEntname() == null ? other.getEntname() == null : this.getEntname().equals(other.getEntname()))
            && (this.getEntlocation() == null ? other.getEntlocation() == null : this.getEntlocation().equals(other.getEntlocation()))
            && (this.getEntbusiness() == null ? other.getEntbusiness() == null : this.getEntbusiness().equals(other.getEntbusiness()))
            && (this.getEntperson() == null ? other.getEntperson() == null : this.getEntperson().equals(other.getEntperson()))
            && (this.getEnttype() == null ? other.getEnttype() == null : this.getEnttype().equals(other.getEnttype()))
            && (this.getInterviewstudent() == null ? other.getInterviewstudent() == null : this.getInterviewstudent().equals(other.getInterviewstudent()))
            && (this.getInterviewaspect() == null ? other.getInterviewaspect() == null : this.getInterviewaspect().equals(other.getInterviewaspect()))
            && (this.getStudentclass() == null ? other.getStudentclass() == null : this.getStudentclass().equals(other.getStudentclass()))
            && (this.getEntwhite() == null ? other.getEntwhite() == null : this.getEntwhite().equals(other.getEntwhite()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEntname() == null) ? 0 : getEntname().hashCode());
        result = prime * result + ((getEntlocation() == null) ? 0 : getEntlocation().hashCode());
        result = prime * result + ((getEntbusiness() == null) ? 0 : getEntbusiness().hashCode());
        result = prime * result + ((getEntperson() == null) ? 0 : getEntperson().hashCode());
        result = prime * result + ((getEnttype() == null) ? 0 : getEnttype().hashCode());
        result = prime * result + ((getInterviewstudent() == null) ? 0 : getInterviewstudent().hashCode());
        result = prime * result + ((getInterviewaspect() == null) ? 0 : getInterviewaspect().hashCode());
        result = prime * result + ((getStudentclass() == null) ? 0 : getStudentclass().hashCode());
        result = prime * result + ((getEntwhite() == null) ? 0 : getEntwhite().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", entname=").append(entname);
        sb.append(", entlocation=").append(entlocation);
        sb.append(", entbusiness=").append(entbusiness);
        sb.append(", entperson=").append(entperson);
        sb.append(", enttype=").append(enttype);
        sb.append(", interviewstudent=").append(interviewstudent);
        sb.append(", interviewaspect=").append(interviewaspect);
        sb.append(", studentclass=").append(studentclass);
        sb.append(", entwhite=").append(entwhite);
        sb.append(", remark=").append(remark);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}