package pers.meng.daointerface;


import pers.meng.domain.bean.entInfo;

import java.util.List;
import java.util.Map;

public interface studententInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    int insert(entInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    int insertSelective(entInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    entInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(entInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ent_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(entInfo record);

    List<entInfo> selectByContion(Map map);

    int  selectCount(Map map);
}